### ISSUE TITLE
Exception when writing document when it doesn' t exit yet; Found @ PHPfastcache

### ISSUE THREAD

**Issue by Fabbzz** [couchbase/couchbase-php-client#185]
Hi,

Together with some people we found out that the PHP SDK has an issue itself when writing the document when it doesn't exist in a Couchbase container yet. When you want to write a document the SDK first tries to get the document as well but as it doesn't exist the SDK throws an exception that PHP fast cache handles as well.

The SDK needs a fix that it doesn't throw an exception when the document it want to write - and doesn't exist yet - just writes and doesn't crash.

Reference:

https://github.com/PHPSocialNetwork/phpfastcache/issues/918

**Comment by avsej** [comment]
Hi @Fabbzz, thanks for report. I've copied the ticket into our Jira (https://jira.issues.couchbase.com/browse/PCBC-1013). This ticket will be updated accordingly once the issue will be resolved. You can still use this one for any further communication.

**Comment by avsej** [comment]
I will close this ticket, as it seems to be related to old extension. If the fastcache needs some transcoder that does not apply any transformations and the payload should be treated as just bytes, you can use [`\Couchbase\RawBinaryTranscoder`](https://github.com/couchbase/couchbase-php-client/blob/main/Couchbase/RawBinaryTranscoder.php).
