### ISSUE TITLE
Undefined constant "Couchbase\COUCHBASE_EXTENSION_NAMESPACE"

### ISSUE THREAD

**Issue by srjlewis** [couchbase/couchbase-php-client#193]
I am getting to following error when calling ```public static function notifyFork(string $event)```

```
Error Object
(
    [message:protected] => Undefined constant "Couchbase\COUCHBASE_EXTENSION_NAMESPACE"
    [string:Error:private] =>.
    [code:protected] => 0
    [file:protected] => /opt/xxx/api/vendor/couchbase/couchbase/Couchbase/Cluster.php
    [line:protected] => 141
)
```

**Comment by srjlewis** [comment]
I have done a bit more testing. 

I am using PHP 8.4, It works with ```"couchbase/couchbase": "4.2.4"```

It looks to be related to #187

**Comment by avsej** [comment]
@srjlewis thank you for your report. I will look into it and report shortly

**Comment by srjlewis** [comment]
@avsej  I have figured out what is causing the issue, we use lazy loading for our caching drivers.

I some instances we are forking the process before calling any caching calls, so a `Cluster` object has not been initialized.

But since `Cluster::notifyFork()` is a static call and can be called independent of a `Cluster` object being initialized, so should not be depentant on a defined value that is only set when a `Cluster` object is created.

Hope the above is helpful
